default:
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters/rust-dfinity-build-ci:latest@sha256:17297ff583f9043c23807657341a33f90651f3bd607405a0cc26413ceee74018
  tags:
    - docker
  interruptible: true
  before_script:
    - dfx --version
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure

cache:
  - key: "dfx-$CI_COMMIT_REF_SLUG"
    paths:
      - .dfx

stages:
  - preparation
  - lint
  - build
  - test
  - integration_testing
  - deploy

include:
  # Templates:
  - local: scripts/ci-cd/.node_template.yml
  - local: scripts/ci-cd/.rust_template.yml
  # Frontend linters:
  - local: scripts/ci-cd/.frontend_linter.yml
    inputs:
      src-folder: claimlink_frontend
  # Unit tests
  - local: scripts/ci-cd/.libraries_unit_test_coverage.yml
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: claimlink
  # Integration tests
  - local: scripts/ci-cd/.integration_tests.yml
  # Canister builds
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: claimlink
  # Frontend builds
  - local: scripts/ci-cd/.frontend_builds.yml
    inputs:
      src-folder: claimlink_frontend
  # Backend deployments
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: claimlink
  # Frontend deployments
  - local: scripts/ci-cd/.frontend_deploys.yml
    inputs:
      src-folder: claimlink_frontend

################################################################################
# Cache preparation
################################################################################
node cache:
  stage: preparation
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "./frontend/{**,**/**,**/**/**}/*.{js,json,jsx,md,mdx,css,html,svg}"
  extends: .node template
  script:
    - npm pkg get name description author license workspaces engines
    - node --version
    - npm --version

################################################################################
# Linters
################################################################################

# See includes above for frontends lint

rust lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
  extends: .rust template
  script:
    - cargo clippy

################################################################################
# Deployments
################################################################################
check canister ids:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        TARGET_NETWORK: staging
        PEM_FILE: "${PEM_FILE_STAGING}"
    - if: $CI_COMMIT_TAG =~ '/^(claimlink|claimlink_frontend)-v\d+\.\d+\.\d+$/'
      variables:
        TARGET_NETWORK: ic
        PEM_FILE: "${PEM_FILE_PRODUCTION}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - scripts/pre-deploy.sh --network $TARGET_NETWORK
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-canister-ids"
    paths:
      - canister_ids.json
    expire_in: 1 hour

claimlink staging:
  stage: deploy
  resource_group: backend canister staging deployment
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "backend/libraries/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/external_canisters/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/canisters/claimlink/{**,**/**,**/**/**}/*.{rs,toml,lock}"
  variables:
    TARGET_NETWORK: staging
    PEM_FILE: "${PEM_FILE_STAGING}"
  needs: ["claimlink staging build"]
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - . scripts/canister-deploy/deploy-claimlink.sh --reinstall $TARGET_NETWORK
  environment:
    name: claimlink
    deployment_tier: staging
    url: https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.icp0.io/?id=jpuy7-oiaaa-aaaan-qmheq-cai # TODO: update this
    action: start

claimlink:
  stage: deploy
  resource_group: backend canister staging deployment
  rules:
    - if: $CI_COMMIT_TAG =~ '/^claimlink-v\d+\.\d+\.\d+$/'
      changes:
        - "backend/libraries/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/external_canisters/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/canisters/claimlink/{**,**/**,**/**/**}/*.{rs,toml,lock}"
      when: manual
  variables:
    TARGET_NETWORK: ic
    PEM_FILE: "${PEM_FILE_PRODUCTION}"
  needs: ["claimlink canister build"]
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - . scripts/canister-deploy/deploy-claimlink.sh $TARGET_NETWORK
  environment:
    name: claimlink
    deployment_tier: production
    url: https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.icp0.io/?id=yuijc-oiaaa-aaaap-ahezq-cai # TODO: update this
    action: start

#######
# DEPLOYMENTS FRONTEND
#######

claimlink_frontend staging:
  stage: deploy
  resource_group: frontend staging deployment
  variables:
    CANISTER_NAME: "claimlink_frontend"
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/claimlink_frontend/*.{js,json}"
        - "frontend/claimlink_frontend/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["claimlink_frontend staging build"]
      variables:
        TARGET_NETWORK: staging
        PEM_FILE: "${PEM_FILE_STAGING}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister staging deploy, script]
  environment:
    name: claimlink_frontend
    deployment_tier: staging
    url: https://7ekbt-siaaa-aaaag-ak64a-cai.icp0.io/ # TODO: update this
    action: start

claimlink_frontend production:
  stage: deploy
  resource_group: frontend production deployment
  variables:
    CANISTER_NAME: "claimlink_frontend"
  rules:
    - if: $CI_COMMIT_TAG =~ '/^claimlink_frontend-v\d+\.\d+\.\d+$/'
      changes:
        - "frontend/claimlink_frontend/*.{js,json}"
        - "frontend/claimlink_frontend/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["claimlink_frontend production build"]
      variables:
        TARGET_NETWORK: ic
        PEM_FILE: "${PEM_FILE_PRODUCTION}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister production deploy, script]
  environment:
    name: claimlink_frontend
    deployment_tier: production
    url: https://jbj2y-2qaaa-aaaal-ajc5q-cai.icp0.io/ # TODO: update this
    action: start
