spec:
  inputs:
    src-folder:
      description: Name of the source folder, should be the same as the canister's cargo package name.
      options: ["claimlink"]
---
# Rust canisters deployments

$[[ inputs.src-folder ]] staging deploy:
  stage: deploy
  resource_group: staging
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event" # deployment when merged to develop
      changes:
        - "backend/canisters/$[[ inputs.src-folder ]]/**/*.{rs,toml,lock,md,did,wasm,gz}"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "develop" # deployment when trigger manually on MR
      changes:
        - "backend/canisters/$[[ inputs.src-folder ]]/**/*.{rs,toml,lock,md,did,wasm,gz}"
      allow_failure: true
      when: manual
  needs:
    ["$[[ inputs.src-folder ]] staging build"]
    # ["$[[ inputs.src-folder ]] staging build", "integration tests"]
  variables:
    TARGET_NETWORK: staging
    PEM_FILE: "${PEM_FILE_STAGING}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - . scripts/canister-deploy/deploy-$[[ inputs.src-folder ]].sh $TARGET_NETWORK
  environment:
    name: $[[ inputs.src-folder ]]
    deployment_tier: staging
    action: start

$[[ inputs.src-folder ]] production deploy:
  stage: deploy
  resource_group: production
  rules:
    - if: $CI_COMMIT_TAG =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+(-reinstall)?$/'
      changes:
        - "backend/libraries/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/external_canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/canisters/$[[ inputs.src-folder ]]/**/*.{rs,toml,lock,md,did,wasm,gz}"
      when: manual
  variables:
    TARGET_NETWORK: ic
    PEM_FILE: "${PEM_FILE_PRODUCTION}"
  needs: ["$[[ inputs.src-folder ]] production build", "integration tests"]
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - . scripts/canister-deploy/deploy-$[[ inputs.src-folder ]].sh $TARGET_NETWORK
  environment:
    name: $[[ inputs.src-folder ]]
    deployment_tier: production
    action: start
