spec:
  inputs:
    src-folder:
      description: Name of the source folder, should be the same as the canister's cargo package name.
      options: ["claimlink"]
---
# Rust canister unit test with coverage

$[[ inputs.src-folder ]] unit tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "backend/libraries/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/external_canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/canisters/$[[ inputs.src-folder ]]/**/*.{rs,toml,lock,md,did,wasm,gz}"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
  extends: .rust template
  script:
    - |
      set -e
      status=0
      for crate in $(find backend/canisters/$[[inputs.src-folder]] -name Cargo.toml -exec dirname {} \;); do
        echo "📦 Running tests in $crate"
        (cd "$crate" && cargo test) || status=1
      done
      exit $status
