spec:
  inputs:
    src-folder:
      description: The frontend project folder name. Must be located in the /frontend/ folder
      options: ["claimlink_dashboard"]
---
# Frontend builds

$[[ inputs.src-folder ]] test build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "frontend/$[[ inputs.src-folder ]]/*.{js,json}"
        - "frontend/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate test declarations"]
  extends: .node template
  script:
    - pnpm build:staging
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]-TEST"
    paths:
      - frontend/$[[ inputs.src-folder ]]/dist
    expire_in: 1 day

$[[ inputs.src-folder ]] staging build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/$[[ inputs.src-folder ]]/*.{js,json}"
        - "frontend/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "staging"
  script:
    - pnpm build:staging
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_STAGING_BUILD"
    paths:
      - frontend/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 1 day
  environment:
    name: $[[ inputs.src-folder ]] frontend app
    deployment_tier: staging
    action: prepare

$[[ inputs.src-folder ]] preprod build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/$[[ inputs.src-folder ]]/*.{js,json}"
        - "frontend/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "preprod"
  script:
    - pnpm build:preprod
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_PREPROD_BUILD"
    paths:
      - frontend/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 1 day
  environment:
    name: $[[ inputs.src-folder ]] frontend app preprod
    deployment_tier: staging
    action: prepare

$[[ inputs.src-folder ]] production build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+$/'
    - if: $CI_COMMIT_REF_NAME == "master"
      changes:
        - "frontend/$[[ inputs.src-folder ]]/*.{js,json}"
        - "frontend/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "ic"
  script:
    - pnpm build:production
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]"
    paths:
      - frontend/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 6 months
  environment:
    name: $[[ inputs.src-folder ]] frontend app
    deployment_tier: production
    action: prepare
