integration tests trigger:
  stage: integration_testing
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "develop"
      changes:
        - "backend/libraries/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/external_canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/integration_testing/**/*.{rs,toml,lock,md,did,wasm,gz}"
      when: manual
  script:
    - echo "Running integration tests"

integration tests:
  stage: integration_testing
  variables:
    KUBERNETES_MEMORY_LIMIT: "5Gi"
    KUBERNETES_MEMORY_REQUEST: "5Gi"
    KUBERNETES_CPU_LIMIT: "2"
    KUBERNETES_CPU_REQUEST: "1"
  rules:
    - if: >
        $CI_COMMIT_TAG =~ '/^[a-zA-Z0-9_]+-v\d+\.\d+\.\d+(-reinstall)?$/'
      when: always
    - if: $CI_COMMIT_REF_NAME == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "backend/libraries/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/external_canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/canisters/**/*.{rs,toml,lock,md,did,wasm,gz}"
        - "backend/integration_tests/**/*.{rs,toml,lock,md,did,wasm,gz}"
  needs: ["claimlink integration-test build"]
  extends: .rust template
  script:
    - wget -O pocket-ic.gz https://github.com/dfinity/pocketic/releases/download/9.0.1/pocket-ic-x86_64-linux.gz
    - gzip -d pocket-ic.gz
    - chmod +x ./pocket-ic
    - mv ./pocket-ic ./backend/integration_tests/pocket-ic
    - ulimit -n 809600
    - ulimit -f 8096000
    - cargo test -p integration_tests
