# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    # - big
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters/rust-dfinity-build-ci:latest@sha256:2cf54ad0b0929a80da25218cd2e05b7a327ed5d038957511fceffe337c2af525
  before_script:
    - cargo --version
    - rustc --version
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure
