# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    # - big
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters/rust-dfinity-build-ci:latest@sha256:17297ff583f9043c23807657341a33f90651f3bd607405a0cc26413ceee74018
  before_script:
    - cargo --version
    - rustc --version
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure
