[package]
name = "claimlink_api"
version = "0.1.0"
description = "API for claimlink canister."
edition = "2021"

[features]
inttest = []

[dependencies]
candid = { workspace = true }
canister_logger = { path = '../../../libraries/canister_logger' }
canister_state_macros = { path = '../../../libraries/canister_state_macros' }
canister_time = { path = '../../../libraries/canister_time' }
canister_tracing_macros = { path = '../../../libraries/canister_tracing_macros' }
serde = { workspace = true, features = ["derive"] }
types = { path = '../../../libraries/types' }
