/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as NewPasswordRouteImport } from './routes/new-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateCertificateIdRouteImport } from './routes/certificate/$certificateId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedMint_certificateIndexRouteImport } from './routes/_authenticated/mint_certificate/index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates/new'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates/$templateId'
import { Route as AuthenticatedMint_certificateTestRouteImport } from './routes/_authenticated/mint_certificate/test'
import { Route as AuthenticatedMint_certificateNewRouteImport } from './routes/_authenticated/mint_certificate/new'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections/new'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns/new'
import { Route as AuthenticatedAccountTransactionHistoryRouteImport } from './routes/_authenticated/account/transaction-history'
import { Route as AuthenticatedAccountNewRouteImport } from './routes/_authenticated/account/new'
import { Route as AuthenticatedAccountEdit_userRouteImport } from './routes/_authenticated/account/edit_user'
import { Route as AuthenticatedAccountEdit_companyRouteImport } from './routes/_authenticated/account/edit_company'
import { Route as AuthenticatedMint_certificateCertificateIdIndexRouteImport } from './routes/_authenticated/mint_certificate/$certificateId/index'
import { Route as AuthenticatedCollectionsCollectionIdIndexRouteImport } from './routes/_authenticated/collections/$collectionId/index'
import { Route as AuthenticatedCampaignsCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/$campaigns/index'
import { Route as AuthenticatedMint_certificateCertificateIdEditRouteImport } from './routes/_authenticated/mint_certificate/$certificateId/edit'
import { Route as AuthenticatedCollectionsCollectionIdEditRouteImport } from './routes/_authenticated/collections/$collectionId/edit'
import { Route as AuthenticatedCampaignsCampaignsClaimersRouteImport } from './routes/_authenticated/campaigns/$campaigns/claimers'
import { Route as AuthenticatedAccountUsersUserIdRouteImport } from './routes/_authenticated/account/users.$userId'
import { Route as AuthenticatedAccountTransactionsTransactionIdRouteImport } from './routes/_authenticated/account/transactions.$transactionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasswordRoute = NewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCertificateIdRoute =
  CertificateCertificateIdRouteImport.update({
    id: '/certificate/$certificateId',
    path: '/certificate/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMint_certificateIndexRoute =
  AuthenticatedMint_certificateIndexRouteImport.update({
    id: '/mint_certificate/',
    path: '/mint_certificate/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMint_certificateTestRoute =
  AuthenticatedMint_certificateTestRouteImport.update({
    id: '/mint_certificate/test',
    path: '/mint_certificate/test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMint_certificateNewRoute =
  AuthenticatedMint_certificateNewRouteImport.update({
    id: '/mint_certificate/new',
    path: '/mint_certificate/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountTransactionHistoryRoute =
  AuthenticatedAccountTransactionHistoryRouteImport.update({
    id: '/account/transaction-history',
    path: '/account/transaction-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountNewRoute = AuthenticatedAccountNewRouteImport.update({
  id: '/account/new',
  path: '/account/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountEdit_userRoute =
  AuthenticatedAccountEdit_userRouteImport.update({
    id: '/account/edit_user',
    path: '/account/edit_user',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountEdit_companyRoute =
  AuthenticatedAccountEdit_companyRouteImport.update({
    id: '/account/edit_company',
    path: '/account/edit_company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMint_certificateCertificateIdIndexRoute =
  AuthenticatedMint_certificateCertificateIdIndexRouteImport.update({
    id: '/mint_certificate/$certificateId/',
    path: '/mint_certificate/$certificateId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdIndexRoute =
  AuthenticatedCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignsIndexRoute =
  AuthenticatedCampaignsCampaignsIndexRouteImport.update({
    id: '/campaigns/$campaigns/',
    path: '/campaigns/$campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMint_certificateCertificateIdEditRoute =
  AuthenticatedMint_certificateCertificateIdEditRouteImport.update({
    id: '/mint_certificate/$certificateId/edit',
    path: '/mint_certificate/$certificateId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdEditRoute =
  AuthenticatedCollectionsCollectionIdEditRouteImport.update({
    id: '/collections/$collectionId/edit',
    path: '/collections/$collectionId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignsClaimersRoute =
  AuthenticatedCampaignsCampaignsClaimersRouteImport.update({
    id: '/campaigns/$campaigns/claimers',
    path: '/campaigns/$campaigns/claimers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountUsersUserIdRoute =
  AuthenticatedAccountUsersUserIdRouteImport.update({
    id: '/account/users/$userId',
    path: '/account/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountTransactionsTransactionIdRoute =
  AuthenticatedAccountTransactionsTransactionIdRouteImport.update({
    id: '/account/transactions/$transactionId',
    path: '/account/transactions/$transactionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/account/edit_company': typeof AuthenticatedAccountEdit_companyRoute
  '/account/edit_user': typeof AuthenticatedAccountEdit_userRoute
  '/account/new': typeof AuthenticatedAccountNewRoute
  '/account/transaction-history': typeof AuthenticatedAccountTransactionHistoryRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/mint_certificate/new': typeof AuthenticatedMint_certificateNewRoute
  '/mint_certificate/test': typeof AuthenticatedMint_certificateTestRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/mint_certificate': typeof AuthenticatedMint_certificateIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/account/transactions/$transactionId': typeof AuthenticatedAccountTransactionsTransactionIdRoute
  '/account/users/$userId': typeof AuthenticatedAccountUsersUserIdRoute
  '/campaigns/$campaigns/claimers': typeof AuthenticatedCampaignsCampaignsClaimersRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/mint_certificate/$certificateId/edit': typeof AuthenticatedMint_certificateCertificateIdEditRoute
  '/campaigns/$campaigns': typeof AuthenticatedCampaignsCampaignsIndexRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/mint_certificate/$certificateId': typeof AuthenticatedMint_certificateCertificateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/account/edit_company': typeof AuthenticatedAccountEdit_companyRoute
  '/account/edit_user': typeof AuthenticatedAccountEdit_userRoute
  '/account/new': typeof AuthenticatedAccountNewRoute
  '/account/transaction-history': typeof AuthenticatedAccountTransactionHistoryRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/mint_certificate/new': typeof AuthenticatedMint_certificateNewRoute
  '/mint_certificate/test': typeof AuthenticatedMint_certificateTestRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/mint_certificate': typeof AuthenticatedMint_certificateIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/account/transactions/$transactionId': typeof AuthenticatedAccountTransactionsTransactionIdRoute
  '/account/users/$userId': typeof AuthenticatedAccountUsersUserIdRoute
  '/campaigns/$campaigns/claimers': typeof AuthenticatedCampaignsCampaignsClaimersRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/mint_certificate/$certificateId/edit': typeof AuthenticatedMint_certificateCertificateIdEditRoute
  '/campaigns/$campaigns': typeof AuthenticatedCampaignsCampaignsIndexRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/mint_certificate/$certificateId': typeof AuthenticatedMint_certificateCertificateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
  '/_authenticated/account/edit_company': typeof AuthenticatedAccountEdit_companyRoute
  '/_authenticated/account/edit_user': typeof AuthenticatedAccountEdit_userRoute
  '/_authenticated/account/new': typeof AuthenticatedAccountNewRoute
  '/_authenticated/account/transaction-history': typeof AuthenticatedAccountTransactionHistoryRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/mint_certificate/new': typeof AuthenticatedMint_certificateNewRoute
  '/_authenticated/mint_certificate/test': typeof AuthenticatedMint_certificateTestRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/mint_certificate/': typeof AuthenticatedMint_certificateIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/account/transactions/$transactionId': typeof AuthenticatedAccountTransactionsTransactionIdRoute
  '/_authenticated/account/users/$userId': typeof AuthenticatedAccountUsersUserIdRoute
  '/_authenticated/campaigns/$campaigns/claimers': typeof AuthenticatedCampaignsCampaignsClaimersRoute
  '/_authenticated/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/_authenticated/mint_certificate/$certificateId/edit': typeof AuthenticatedMint_certificateCertificateIdEditRoute
  '/_authenticated/campaigns/$campaigns/': typeof AuthenticatedCampaignsCampaignsIndexRoute
  '/_authenticated/collections/$collectionId/': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/_authenticated/mint_certificate/$certificateId/': typeof AuthenticatedMint_certificateCertificateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/terms'
    | '/dashboard'
    | '/certificate/$certificateId'
    | '/account/edit_company'
    | '/account/edit_user'
    | '/account/new'
    | '/account/transaction-history'
    | '/campaigns/new'
    | '/collections/new'
    | '/mint_certificate/new'
    | '/mint_certificate/test'
    | '/templates/$templateId'
    | '/templates/new'
    | '/account'
    | '/campaigns'
    | '/collections'
    | '/mint_certificate'
    | '/templates'
    | '/account/transactions/$transactionId'
    | '/account/users/$userId'
    | '/campaigns/$campaigns/claimers'
    | '/collections/$collectionId/edit'
    | '/mint_certificate/$certificateId/edit'
    | '/campaigns/$campaigns'
    | '/collections/$collectionId'
    | '/mint_certificate/$certificateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/terms'
    | '/dashboard'
    | '/certificate/$certificateId'
    | '/account/edit_company'
    | '/account/edit_user'
    | '/account/new'
    | '/account/transaction-history'
    | '/campaigns/new'
    | '/collections/new'
    | '/mint_certificate/new'
    | '/mint_certificate/test'
    | '/templates/$templateId'
    | '/templates/new'
    | '/account'
    | '/campaigns'
    | '/collections'
    | '/mint_certificate'
    | '/templates'
    | '/account/transactions/$transactionId'
    | '/account/users/$userId'
    | '/campaigns/$campaigns/claimers'
    | '/collections/$collectionId/edit'
    | '/mint_certificate/$certificateId/edit'
    | '/campaigns/$campaigns'
    | '/collections/$collectionId'
    | '/mint_certificate/$certificateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/certificate/$certificateId'
    | '/_authenticated/account/edit_company'
    | '/_authenticated/account/edit_user'
    | '/_authenticated/account/new'
    | '/_authenticated/account/transaction-history'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/collections/new'
    | '/_authenticated/mint_certificate/new'
    | '/_authenticated/mint_certificate/test'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/templates/new'
    | '/_authenticated/account/'
    | '/_authenticated/campaigns/'
    | '/_authenticated/collections/'
    | '/_authenticated/mint_certificate/'
    | '/_authenticated/templates/'
    | '/_authenticated/account/transactions/$transactionId'
    | '/_authenticated/account/users/$userId'
    | '/_authenticated/campaigns/$campaigns/claimers'
    | '/_authenticated/collections/$collectionId/edit'
    | '/_authenticated/mint_certificate/$certificateId/edit'
    | '/_authenticated/campaigns/$campaigns/'
    | '/_authenticated/collections/$collectionId/'
    | '/_authenticated/mint_certificate/$certificateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewPasswordRoute: typeof NewPasswordRoute
  TermsRoute: typeof TermsRoute
  CertificateCertificateIdRoute: typeof CertificateCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-password': {
      id: '/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof NewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$certificateId': {
      id: '/certificate/$certificateId'
      path: '/certificate/$certificateId'
      fullPath: '/certificate/$certificateId'
      preLoaderRoute: typeof CertificateCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mint_certificate/': {
      id: '/_authenticated/mint_certificate/'
      path: '/mint_certificate'
      fullPath: '/mint_certificate'
      preLoaderRoute: typeof AuthenticatedMint_certificateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mint_certificate/test': {
      id: '/_authenticated/mint_certificate/test'
      path: '/mint_certificate/test'
      fullPath: '/mint_certificate/test'
      preLoaderRoute: typeof AuthenticatedMint_certificateTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mint_certificate/new': {
      id: '/_authenticated/mint_certificate/new'
      path: '/mint_certificate/new'
      fullPath: '/mint_certificate/new'
      preLoaderRoute: typeof AuthenticatedMint_certificateNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/transaction-history': {
      id: '/_authenticated/account/transaction-history'
      path: '/account/transaction-history'
      fullPath: '/account/transaction-history'
      preLoaderRoute: typeof AuthenticatedAccountTransactionHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/new': {
      id: '/_authenticated/account/new'
      path: '/account/new'
      fullPath: '/account/new'
      preLoaderRoute: typeof AuthenticatedAccountNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/edit_user': {
      id: '/_authenticated/account/edit_user'
      path: '/account/edit_user'
      fullPath: '/account/edit_user'
      preLoaderRoute: typeof AuthenticatedAccountEdit_userRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/edit_company': {
      id: '/_authenticated/account/edit_company'
      path: '/account/edit_company'
      fullPath: '/account/edit_company'
      preLoaderRoute: typeof AuthenticatedAccountEdit_companyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mint_certificate/$certificateId/': {
      id: '/_authenticated/mint_certificate/$certificateId/'
      path: '/mint_certificate/$certificateId'
      fullPath: '/mint_certificate/$certificateId'
      preLoaderRoute: typeof AuthenticatedMint_certificateCertificateIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/': {
      id: '/_authenticated/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaigns/': {
      id: '/_authenticated/campaigns/$campaigns/'
      path: '/campaigns/$campaigns'
      fullPath: '/campaigns/$campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mint_certificate/$certificateId/edit': {
      id: '/_authenticated/mint_certificate/$certificateId/edit'
      path: '/mint_certificate/$certificateId/edit'
      fullPath: '/mint_certificate/$certificateId/edit'
      preLoaderRoute: typeof AuthenticatedMint_certificateCertificateIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/edit': {
      id: '/_authenticated/collections/$collectionId/edit'
      path: '/collections/$collectionId/edit'
      fullPath: '/collections/$collectionId/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaigns/claimers': {
      id: '/_authenticated/campaigns/$campaigns/claimers'
      path: '/campaigns/$campaigns/claimers'
      fullPath: '/campaigns/$campaigns/claimers'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignsClaimersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/users/$userId': {
      id: '/_authenticated/account/users/$userId'
      path: '/account/users/$userId'
      fullPath: '/account/users/$userId'
      preLoaderRoute: typeof AuthenticatedAccountUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/transactions/$transactionId': {
      id: '/_authenticated/account/transactions/$transactionId'
      path: '/account/transactions/$transactionId'
      fullPath: '/account/transactions/$transactionId'
      preLoaderRoute: typeof AuthenticatedAccountTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAccountEdit_companyRoute: typeof AuthenticatedAccountEdit_companyRoute
  AuthenticatedAccountEdit_userRoute: typeof AuthenticatedAccountEdit_userRoute
  AuthenticatedAccountNewRoute: typeof AuthenticatedAccountNewRoute
  AuthenticatedAccountTransactionHistoryRoute: typeof AuthenticatedAccountTransactionHistoryRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
  AuthenticatedMint_certificateNewRoute: typeof AuthenticatedMint_certificateNewRoute
  AuthenticatedMint_certificateTestRoute: typeof AuthenticatedMint_certificateTestRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedMint_certificateIndexRoute: typeof AuthenticatedMint_certificateIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedAccountTransactionsTransactionIdRoute: typeof AuthenticatedAccountTransactionsTransactionIdRoute
  AuthenticatedAccountUsersUserIdRoute: typeof AuthenticatedAccountUsersUserIdRoute
  AuthenticatedCampaignsCampaignsClaimersRoute: typeof AuthenticatedCampaignsCampaignsClaimersRoute
  AuthenticatedCollectionsCollectionIdEditRoute: typeof AuthenticatedCollectionsCollectionIdEditRoute
  AuthenticatedMint_certificateCertificateIdEditRoute: typeof AuthenticatedMint_certificateCertificateIdEditRoute
  AuthenticatedCampaignsCampaignsIndexRoute: typeof AuthenticatedCampaignsCampaignsIndexRoute
  AuthenticatedCollectionsCollectionIdIndexRoute: typeof AuthenticatedCollectionsCollectionIdIndexRoute
  AuthenticatedMint_certificateCertificateIdIndexRoute: typeof AuthenticatedMint_certificateCertificateIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAccountEdit_companyRoute: AuthenticatedAccountEdit_companyRoute,
  AuthenticatedAccountEdit_userRoute: AuthenticatedAccountEdit_userRoute,
  AuthenticatedAccountNewRoute: AuthenticatedAccountNewRoute,
  AuthenticatedAccountTransactionHistoryRoute:
    AuthenticatedAccountTransactionHistoryRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  AuthenticatedMint_certificateNewRoute: AuthenticatedMint_certificateNewRoute,
  AuthenticatedMint_certificateTestRoute:
    AuthenticatedMint_certificateTestRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedMint_certificateIndexRoute:
    AuthenticatedMint_certificateIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedAccountTransactionsTransactionIdRoute:
    AuthenticatedAccountTransactionsTransactionIdRoute,
  AuthenticatedAccountUsersUserIdRoute: AuthenticatedAccountUsersUserIdRoute,
  AuthenticatedCampaignsCampaignsClaimersRoute:
    AuthenticatedCampaignsCampaignsClaimersRoute,
  AuthenticatedCollectionsCollectionIdEditRoute:
    AuthenticatedCollectionsCollectionIdEditRoute,
  AuthenticatedMint_certificateCertificateIdEditRoute:
    AuthenticatedMint_certificateCertificateIdEditRoute,
  AuthenticatedCampaignsCampaignsIndexRoute:
    AuthenticatedCampaignsCampaignsIndexRoute,
  AuthenticatedCollectionsCollectionIdIndexRoute:
    AuthenticatedCollectionsCollectionIdIndexRoute,
  AuthenticatedMint_certificateCertificateIdIndexRoute:
    AuthenticatedMint_certificateCertificateIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewPasswordRoute: NewPasswordRoute,
  TermsRoute: TermsRoute,
  CertificateCertificateIdRoute: CertificateCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
