use std::panic;

use claimlink_api::init::ClaimlinkArgs;
use ic_cdk_macros::init;
use tracing::info;

use crate::{state::RuntimeState, storage::record_nft_collection_wasm};

use super::init_canister;

#[init]
fn init(args: ClaimlinkArgs) {
    let args = match args {
        ClaimlinkArgs::InitArg(init_arg) => init_arg,
        ClaimlinkArgs::UpgradeArg(_upgrade_arg) => panic!("Upgrade arg at the time initialization"),
    };

    bity_ic_canister_logger::init(args.test_mode);

    // generate the state from init args
    let mut state = RuntimeState::try_from(args).expect("Failed to generate canister state");

    // Add the first ogy nft wasm to wasm store.
    // Wasmhash is generated by wasms located in wasms directory.
    let origyn_nft_wasm_hash = record_nft_collection_wasm();

    state.data.origyn_nft_wasm_hash = origyn_nft_wasm_hash;

    init_canister(state);

    info!("Init complete.")
}
