use std::panic;

pub use claimlink_api::types::lifecycle::ClaimlinkArgs;
use ic_cdk_macros::init;
use tracing::info;

use crate::{
    setup_timers,
    state::RuntimeState,
    storage::{events::record_event, record_nft_collection_wasm},
    types::events::EventType,
};

use super::init_canister;

#[init]
fn init(args: ClaimlinkArgs) {
    let args = match args {
        ClaimlinkArgs::InitArg(init_arg) => init_arg,
        ClaimlinkArgs::UpgradeArg(_upgrade_arg) => panic!("Upgrade arg at the time initialization"),
    };

    bity_ic_canister_logger::init(args.test_mode);

    // generate the state from init args
    let mut state =
        RuntimeState::try_from(args.clone()).expect("Failed to generate canister state");
    record_event(EventType::Init(args));

    // Add the first ogy nft wasm to wasm store.
    // Wasmhash is generated by wasms located in wasms directory.
    let origyn_nft_wasm_hash = record_nft_collection_wasm();

    state.data.origyn_nft_wasm_hash = origyn_nft_wasm_hash;

    init_canister(state);

    setup_timers();

    info!("Init complete.")
}
